name: Cybersecurity Podcast Automation

on:
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 7 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser newspaper3k openai google-cloud-texttospeech requests

      - name: Collect News
        run: python news_collector.py

      - name: Filter Top Articles
        run: python relevancy_filter.py

      - name: Summarize News
        run: python summarizer.py

      - name: Create Medium Post
        env:
          MEDIUM_API_TOKEN: ${{ secrets.MEDIUM_API_TOKEN }}
        run: python medium_post_creator.py

      - name: Generate Podcast Script
        run: python podcast_script_generator.py

      - name: Record Podcast
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python podcast_recorder.py

      - name: Upload Podcast
        env:
          PODBEAN_ACCESS_TOKEN: ${{ secrets.PODBEAN_ACCESS_TOKEN }}
        run: python podcast_uploader.py
